### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by poolarrr** [RUCAIBox/RecBole-PJF#1]
您好，我在运行DPGNN、IPJF、SHPJF时都会提示KeyError。
DPGNN报错：
![image](https://user-images.githubusercontent.com/81065773/191413096-e16cbf4e-b68d-45af-8b4b-f31a097b6469.png)
IPJF报错：
![image](https://user-images.githubusercontent.com/81065773/191413118-1bb025cd-b0a5-4252-aa73-47f948c57bd1.png)
SHPJF报错：
![image](https://user-images.githubusercontent.com/81065773/191413140-31009ade-a0a6-4b68-93bd-2d51d712cf0b.png)
请问下这是在yaml文件中修改参数即可还是需要在dataset.py文件中修改？

**Comment by flust** [comment]
DPGNN和IPJF可能是dataloader部分没有正确加载，neg_user_id和neu_job_id都是特殊的采样方式，可以先检查一下dataloader。然后SHPJF的qwd_his应该是搜索历史，需要特定的数据（目前这部分数据没有公开可用的），具体的数据格式可能需要看一下源代码。
抱歉之前没看到这条issue，我再把代码检查一下，后面有问题可以再问我

**Comment by Lotus-Blue** [comment]
> DPGNN和IPJF可能是dataloader部分没有正确加载，neg_user_id和neu_job_id都是特殊的采样方式，可以先检查一下dataloader。然后SHPJF的qwd_his应该是搜索历史，需要特定的数据（目前这部分数据没有公开可用的），具体的数据格式可能需要看一下源代码。 抱歉之前没看到这条issue，我再把代码检查一下，后面有问题可以再问我

SHPJF现在还有这个问题

**Comment by Lotus-Blue** [comment]
> DPGNN和IPJF可能是dataloader部分没有正确加载，neg_user_id和neu_job_id都是特殊的采样方式，可以先检查一下dataloader。然后SHPJF的qwd_his应该是搜索历史，需要特定的数据（目前这部分数据没有公开可用的），具体的数据格式可能需要看一下源代码。 抱歉之前没看到这条issue，我再把代码检查一下，后面有问题可以再问我

IPJF目前还提示KeyError: 'neu_job_id'

**Comment by David-soda** [comment]
> 然后SHPJF的qwd_his

请问解决了吗
