### ISSUE TITLE
bert模型没有涉及bert相关内容

### ISSUE THREAD

**Issue by ysf-gd** [RUCAIBox/RecBole-PJF#22]
bert模型中 self.bert_user = nn.Linear(self.embedding_size, self.hidden_size)， self.bert_item = nn.Linear(self.embedding_size, self.hidden_size)哪里体现了bert相关的内容？

**Comment by flust** [comment]
bert的内容体现在dataset里，dataset里把文本处理成向量，然后模型的输入就是文本向量（参考bert.py中的predict和calculate_loss）。这里bert是不训练的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月26日(周一) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [RUCAIBox/RecBole-PJF] bert模型没有涉及bert相关内容 (Issue #22)




 
bert模型中 self.bert_user = nn.Linear(self.embedding_size, self.hidden_size)， self.bert_item = nn.Linear(self.embedding_size, self.hidden_size)哪里体现了bert相关的内容？
