### ISSUE TITLE
您好，我这里可以使用训练好的人岗模型，在一个新的数据集上进行预测吗

### ISSUE THREAD

**Issue by chiazhangzhang** [RUCAIBox/RecBole-PJF#8]
现有问题是，模型训练完毕，需要在自己的数据集上进行测试，岗位、简历都可能是新的数据（训练集中没有的）。可以实现吗？
相当于希望在另一份 test 集上进行测试，重点希望得到新数据上的指标。
如何进行数据加载？模型预测呢？是否有案例进行参考？

**Comment by flust** [comment]
您好，这个问题是这样，仅用文本做匹配的模型在相同的文本预处理的情况下，可以用到其他数据集，具体的处理方式可以参考recbole的文档，通过手动设置train/valid/test集合来实现。其他模型基本都不行，训练数据包含用户行为，比如说你用a用户的行为训练的模型，是无法预测b用户的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月30日(周四) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [RUCAIBox/RecBole-PJF] 您好，我这里可以使用训练好的人岗模型，在一个新的数据集上进行预测吗 (Issue #8)




 
现有问题是，模型训练完毕，需要在自己的数据集上进行测试，岗位、简历都可能是新的数据（训练集中没有的）。可以实现吗？
 相当于希望在另一份 test 集上进行测试，重点希望得到新数据上的指标。
 如何进行数据加载？模型预测呢？是否有案例进行参考？

**Comment by chiazhangzhang** [comment]
可以这样理解吗？
基于内容的匹配模型可以进行预测。然后协同过滤和混合类型的人岗模型，无法进行预测。
